-- MySQL Script generated by MySQL Workbench
-- 12/17/15 02:20:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema databaseprojetonami
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema databaseprojetonami
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `databaseprojetonami` DEFAULT CHARACTER SET utf8 ;
USE `databaseprojetonami` ;

-- -----------------------------------------------------
-- Table `databaseprojetonami`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databaseprojetonami`.`user` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idade` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `patologia` LONGTEXT NULL DEFAULT NULL,
  `programa` VARCHAR(45) NOT NULL,
  `proximaFase` VARCHAR(45) NULL DEFAULT NULL,
  `datacadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `databaseprojetonami`.`fase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databaseprojetonami`.`fase` (
  `idFase` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tempoFinal` FLOAT NOT NULL,
  `concentracao` VARCHAR(45) NULL DEFAULT NULL,
  `quant_erro` INT(11) NULL DEFAULT NULL,
  `dataRealizada` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `User_idUser` INT(11) NOT NULL,
  PRIMARY KEY (`idFase`),
  INDEX `fk_Fase_User_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Fase_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `databaseprojetonami`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
